server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    # true 表示向注册中心注册自己, 将自己注册进EurekaServer 默认为true
    fetch-registry: true
    # true 表示是否从EurekaServer抓取已有信息, 默认为true。单节点无所谓, 集群必须配置为true才能配合ribbon使用负载均衡
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      #集群版, 要将eureka集群内部的多个node都要注册