server:
  port: 80

spring:
  application:
    name: cloud-order-service
  cloud:
    consul:
      # host: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183 集群配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
