server:
  port: 80

spring:
  application:
    name: cloud-order-service
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      # connect-string: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183 集群配置
